### ISSUE TITLE
Error: failed to load external entity "http://biobank.ndph.ox.ac.uk/showcase/list.cgi?it=0&vt=11"

### ISSUE THREAD

**Issue by mbyrska** [umich-cphds/createUKBphenome#3]
Hello, I'm running into the error below when trying to run the function.createUKBphenome.r script. It seems to be caused by line 24 in the function.collectFields.r script. Any advice how to fix this? Thanks so much!

Rscript ./scripts/function.createUKBphenome.r 
[1] "Mapping ICD9 codes to PheCodes"
There were 19 warnings (use warnings() to see them)
[1] "Rollup of phewas codes (ICD9 code)"

             original rolled up PheWAS code 
                18689                  2973 
[1] "Mapping ICD10 codes to PheCodes"
[1] "Rollup of phewas codes (ICD10 code)"

             original rolled up PheWAS code 
                15908                  7030 
[1] "Mapping tables created and stored in ./results/UKB_PHENOME_ICD*_PHECODE_MAP_20201103.txt"
[1] "Collecting UKB fields and data"
Error: failed to load external entity "http://biobank.ndph.ox.ac.uk/showcase/list.cgi?it=0&vt=11"
Execution halted

**Comment by ilarsf** [comment]
Hello, I rewrote `function.collectFields.r` to use a different R library. Also updated URL from http to https.

**Comment by mbyrska** [comment]
Perfect, it works fine now! Thanks a lot for your help!
