### ISSUE TITLE
Error in basename(baskets) :    file name conversion problem -- name too long?

### ISSUE THREAD

**Issue by uhan0211** [umich-cphds/createUKBphenome#4]
Hi there,

Thanks for developing such an amazing tool for PheWAS code mapping. Recently, when we used its function.createUKBphenome.r script to load all baskets, we encountered the following error:
Error in basename(baskets) :    file name conversion problem -- name too long?

The following is my code:
>ukb<-fread("E:/ukb42111.tab")
>fwrite(ukb,"E:/createUKBphenome-master/createUKBphenome-master/data/baskets.txt",quote = F,sep="\t")

>file.baskets <- "./data/baskets.txt"
>if(!file.exists(file.baskets)) stop("Please add file 'baskets.txt' with basket locations to './data/' folder'!")
>baskets <- readLines(file.baskets) 

>str(baskets)
chr [1:502506] "f.eid\tf.3.0.0\tf.3.1.0\tf.3.2.0\tf.3.3.0\tf.4.0.0\tf.4.1.0\tf.4.2.0\tf.4.3.0\tf.5.0.0\tf.5.1.0\tf.5.2.0\tf.5.3".....
>names(baskets) <- basename(baskets)

Could you give me some suggestions to fix it?

Thank you very much!

Best Regards,
Tina

**Comment by ilarsf** [comment]
Hi Tian,

The file "baskets.txt" only needs the baskets' file locations, not the actual data.
In your case this would just be the following line: "E:/ukb42111.tab"

Hope this helps.

Thanks,
Lars

**Comment by uhan0211** [comment]
Thanks for your reply! It can work now!

Best Regards,
Tina
